version: '3.4'

networks:
  app:
   driver: "bridge"

services:
  reverese_proxy:
    container_name: proxy
    image: nginx:latest
    hostname: "nginx"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/proxy.conf:/etc/nginx/proxy.conf:ro
      - ./ssl/localhost.crt:/etc/ssl/certs/localhost.crt:ro
      - ./ssl/localhost.key:/etc/ssl/certs/localhost.key:ro
    ports:
      - "8080:8080"
      - "443:443"
    depends_on:
      - auth
      - api
    networks:
      app:
        aliases:
        - "proxy"

  auth:
    container_name: auth
    image: ${DOCKER_REGISTRY-}identityserver
    environment:
     - ASPNETCORE_SUBDIR=/auth
     - ASPNETCORE_ISSUER_URI=https://localhost/auth
    build:
      context: ..
      dockerfile: src/IdentityServer/Dockerfile
    networks:
      app:
        aliases:
        - "auth_proxy"

  api:
    container_name: api
    image: ${DOCKER_REGISTRY-}api
    environment:
     - "ASPNETCORE_SUBDIR=/api"
    build:
      context: ..
      dockerfile: src/Api/Dockerfile
    networks:
      app:
        aliases:
          - "api"
